[package]
name = "pidgin"
version = "0.1.0"
authors = ["dfhoughton <dfhoughton@gmail.com>"]

[[bin]]
name="pidgin"
path = "src/main.rs"

[dependencies]
regex = "1"
lazy_static = "1.1.0"

[dev-dependencies]
rand = "0.5.5"
criterion = "0.2"

[[bench]]
name = "regex_comparison"
harness = false
